### ISSUE TITLE
`v1.0.5` is not published to npm

### ISSUE THREAD

**Issue by samdotci** [enfuse/backstage-chatgpt-backend#1]
Hey! Just tried this out, but encountered an error on startup owing to the `@backstage/core-plugin-api` import.

It seems like [some changes](https://github.com/enfuse/backstage-chatgpt-backend/commit/d439b0bd3c76838325962d947346ff83202457d2) were made to resolve this issue, but those changes aren't yet published to NPM.

Would greatly appreciate if you could publish v1.0.5. Thank you!

**Comment by chr-enfuse** [comment]
hi @samdotci, thank you for bringing this up to our attention, we published the latest changes of our backend package just. few minutes ago. you can go ahead and try to set it up again.

**Comment by chr-enfuse** [comment]
@samdotci Use v1.0.10 for this onwards, along with @enfuse/chatgpt-plugin-frontend v1.0.14 for compatibility
