### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by Lifter-PL** [enfuse/backstage-chatgpt-backend#3]
When I configure backend acording to README and start `yarn dev`, I get an error like below.

![2023-06-09_12h43_08](https://github.com/enfuse/backstage-chatgpt-backend/assets/31290686/32b807da-5758-4744-81f4-620e7e577341)

`
Versions: 
yarn 1.22.19
node 18.16.0
`

First, changes described in https://github.com/enfuse/backstage-chatgpt-backend/pull/2 need to be applied, because otherwise, earlier errors occur - like plugin not found due to wrong extension of chatgpt file in point 3 of instruction.

I would greatly appreciate any help. Thank you.

**Comment by jaya271999** [comment]
Facing same issue when tried to configure the backend plugin, I have also raised the same issue https://github.com/enfuse/backstage-chatgpt-plugin/issues/2, wanted to know is there something missing in chatgpt.ts file as suggested in https://github.com/backstage/backstage/issues/15314 issue.

**Comment by freben** [comment]
This seems to be a resurfacing of #1 . After adding version 1.0.5 of the package to my backend, `node_modules/@enfuse/plugin-chatgpt-backend/dist/index.cjs.js` contains code like

![Screenshot 2023-06-15 at 13 16 11](https://github.com/enfuse/backstage-chatgpt-backend/assets/3097461/efb587fe-08c6-4f07-8e26-2936804d9c7a)

So it would seem to me that the 1.0.5 release was mistakenly targeting an old code base, because that indeed does not match [what's in the master branch](https://github.com/enfuse/backstage-chatgpt-backend/blob/master/src/service/openai.ts#L19).

**Comment by malagant** [comment]
Any hints on what to do to solve this?

**Comment by Jim-Gloaguen** [comment]
Got past the error by downgrading to 1.0.3 so @freben is definitely on point. But then the frontend broke so the plugin is still unusable on my end. So i guess we are waiting for a 1.0.5 re-release or 1.0.6 with a fix hopefully.

**Comment by jonaselan** [comment]
Same error here. Waiting for a fix 🤞🏽

**Comment by chr-enfuse** [comment]
Hi, thank you for bringing this to our attention, we are working on a solution and we will update you as soon as we have worked out a solution for this.

**Comment by chr-enfuse** [comment]
@Lifter-PL Thank you for the contributions on our README for clarifying installation instructions. We published a new version for the backend plugin (v1.0.10) and it should be used with the UI part of this plugin (v1.0.14) for them to work together.

**Comment by jonaselan** [comment]
@ch-enfuse Thanks for the work in this new version. I testing now and I have some points:

1. Following the docs, I need to change my `chatgpt.ts` to work properly, adding the 'config' in parameters:

```
import { createRouter } from '@enfuse/plugin-chatgpt-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';

export default async function createPlugin({
  logger,
  config,
}: PluginEnvironment): Promise<Router> {
  return await createRouter({
    config,
    logger,
  });
}
```
2. Seems the original error was fixed, but now I have this instead after submit something in the prompt:

![image](https://github.com/enfuse/backstage-chatgpt-backend/assets/5933907/e05eea07-4f1c-48ac-912a-98f80429f83e)

**Comment by sharadpattanshetti** [comment]
After trying above code the compile error is fixed but am getting this error, is there any whitelisting required? 

error": {
"name": "Error",
"message": "socket hang up",
"stack": "Error: socket hang up\n    at connResetException (node:internal/errors:705:14)\n    at Socket.socketOnEnd (node:_http_client:518:23)\n    at Socket.emit (node:events:525:35)\n    at Socket.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
"config": {
"transitional": {
"silentJSONParsing": true,
"forcedJSONParsing": true,
"clarifyTimeoutError": false
},
"transformRequest": [
null
],
"transformResponse": [
null
],
"timeout": 0,
"xsrfCookieName": "XSRF-TOKEN",
"xsrfHeaderName": "X-XSRF-TOKEN",
"maxContentLength": -1,
"maxBodyLength": -1,

**Comment by chr-enfuse** [comment]
We've had some issues publishing our packages with the correct changes. 
Please upgrade the frontend part of this plugin to 1.1.1 and the backend part to 1.1.0. This should resolve all these installation and compatibility issues. 
Thank you for your patience!

**Comment by jonaselantw** [comment]
Thanks again for the patch fix. 
I don't know if is something here, but now I get another error when I start the server. I was trying to install only the backend plugin.

![image](https://github.com/enfuse/backstage-chatgpt-backend/assets/133057177/40dcbb9e-f3c3-4699-a03c-085f35cbe8d3)

**Comment by kv00797898** [comment]
I am seeing the below error. Can you please provide the information how to fix for the issue.

![image](https://github.com/enfuse/backstage-chatgpt-backend/assets/116725840/7c929194-576a-4358-a95d-cfacb04f771b)

**Comment by j03w** [comment]
I think this might have something to do with the fact that the plugin requires older version of itself as a dependency

https://github.com/enfuse/backstage-chatgpt-backend/commit/c350c39ae3b5469529e2f14fa6a1d440a4e861ee

**Comment by simonedstrom96** [comment]
I am also getting this error, fix would be great

> Thanks again for the patch fix. I don't know if is something here, but now I get another error when I start the server. I was trying to install only the backend plugin.
> 
> ![image](https://user-images.githubusercontent.com/133057177/258157648-40dcbb9e-f3c3-4699-a03c-085f35cbe8d3.png)

**Comment by chr-enfuse** [comment]
I would try to uninstalling both frontend and backend packages (from your node modules) and reinstall them again. Also, make sure to have the latest versions of both packages in order to have them working.

**Comment by chr-enfuse** [comment]
@simonedstrom96 @kv00797898 @jonaselantw We discovered an issue with our published package not containing type definitions resulting in this error. You should now be able to download the latest version (1.1.1) for this package and that should take care of this issue.

**Comment by willoh1998** [comment]
Closing the issue, as a fix has been published.
