### ISSUE TITLE
Docs as Code + API + GPT

### ISSUE THREAD

**Issue by fabidick22** [enfuse/backstage-chatgpt-backend#4]
I wonder if it is possible to integrate this plugin with other plugins like DaC or API. This would allow questions such as: What is service X for? What API can I use if I need to get a list of `X` objects? Etc.

It probably makes more sense to start using a [local model](https://github.com/go-skynet/LocalAI) to avoid high costs for GPT API consumption.

**Comment by chr-enfuse** [comment]
Hey @fabidick22, thank you for your suggestion, we'll take it into consideration for future development.

**Comment by willoh1998** [comment]
Closing issue, feedback received!
