### ISSUE TITLE
Bug with plugin setup

### ISSUE THREAD

**Issue by jsidney** [enfuse/backstage-chatgpt-backend#5]
I have just installed the latest version of the plugin and created the `chatgpt.ts` file under plugins. However, my linter is returning the following error:
> Argument of type '{ logger: winston.Logger; }' is not assignable to parameter of type 'RouterOptions'.
  Property 'config' is missing in type '{ logger: winston.Logger; }' but required in type 'RouterOptions'.ts(2345)
index.d.ts(7, 5): 'config' is declared here.

this is what the code looks like:
``` 

import { createRouter } from '@enfuse/plugin-chatgpt-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
  });
}
```

any thoughts?

**Comment by chr-enfuse** [comment]
Hi @jsidney, you need to also reference the configuration from the environment and pass it to the createRouter function like this,

```    
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config
  });
}
```

We updated the installation instructions for this, thank you for bringing this up!

**Comment by jsidney** [comment]
thanks @ch-enfuse ! worked  like a charm!
